### ISSUE TITLE
Failed

### ISSUE THREAD

**Issue by heyalbert** [theofidry/PsyshBundle#1]
Hey,
I tried your Bundle, because I wish also inline psysh with Symfony2, but unfortunately it failed by calling the cmd: php app/console psysh. See below.

Any idea, how I can fix that? Thank you in advance. :-) 

```
  [InvalidArgumentException]
  Command "psysh" is not defined.
```

**Comment by theofidry** [comment]
@heyalbert, I'm sorry I did not see your issue. This was a little test like that I did not do much yet. I'm planning to doing it more seriously this month and provide some doc with it. Sorry for the delay.

**Comment by theofidry** [comment]
The bundle and the doc has been updated. The doc needs a little bit of rewording and should be made more friendly but the gist of it is there.
