### ISSUE TITLE
Allow for psy/psysh v0.6 

### ISSUE THREAD

**Issue by dlancea** [theofidry/PsyshBundle#18]
The composer.json is behind in keeping up with the current psy/psysh version.

Since this is a development only package, I think it makes sense that the psy/psysh version required for this bundle be less restrictive, so that the current version of psy/psysh could keep in pace with this bundle. Something like "^0.5" would be good.

**Comment by dlancea** [comment]
thanks!

**Comment by theofidry** [comment]
No worries, I should have done that long ago, it's a pity Psysh doesn't release a stable version :(
