### ISSUE TITLE
mkdir(): Permission denied when running as unprivileged php-fpm

### ISSUE THREAD

**Issue by teohhanhui** [theofidry/PsyshBundle#23]
psysh tries to creates its history file: https://github.com/bobthecow/psysh/blob/e64e10b20f8d229cac76399e1f3edddb57a0f280/src/Psy/Configuration.php#L384

Which fails because php-fpm doesn't have the permissions to create its config dir in the non-existent home directory (the default of `~/.config/psysh` => `/var/www/.config/psysh`)

**Comment by theofidry** [comment]
Hm, I guess we should change the config to:

1. create its history
2. disable history if does not have the permissions

Not sure if 2. is doable, but I could at least add a param to disable the history
