### ISSUE TITLE
symfony 3.4 deprecation notice

### ISSUE THREAD

**Issue by mkingbe** [theofidry/PsyshBundle#30]
`
 User Deprecated: The "psysh.facade" service is private, getting it from the container is deprecated since Symfony 3.2 and will fail in 4.0. You should either make the service public, or stop using the container directly and use dependency injection instead. {"exception":"[object] (ErrorException(code: 0): User Deprecated: The \"psysh.facade\" service is private, getting it from the container is deprecated since Symfony 3.2 and will fail in 4.0. You should either make the service public, or stop using the container directly and use dependency injection instead. at vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Container.php:275)"} {"uid":"a789e5a"}`

**Comment by theofidry** [comment]
Indeed, could you provide a PR to turn those services into public services?

**Comment by theofidry** [comment]
Fixed in #32
