### ISSUE TITLE
Add a Symfony 4 recipe

### ISSUE THREAD

**Issue by antonmedv** [theofidry/PsyshBundle#34]
Add support for symfony4.

**Comment by theofidry** [comment]
Symfony 4 should already be supported, what issue did you encounter?

**Comment by theofidry** [comment]
Sorry but you'll have to be a bit more descriptive than that as it works for me:

```
composer create-project symfony/skeleton psysh-demo
cd psysh-demo
composer req theofidry/psysh-bundle
bin/console psysh
> PsySH starts...
```

**Comment by antonmedv** [comment]
It works. But config file `config/packages/psysh.yaml` does not created.

**Comment by theofidry** [comment]
I'm not sure why it's not created but I don't know what should be done for the package for it to be created so unless it's an issue for you I would post an issue on the flex repository or look at the code itself to know under what conditions those files are created

**Comment by FGM** [comment]
AIUI, this is performed within Symfony\Flex\Configurator\CopyFromPackageConfigurator::configure(), meaning the bundle needs to have an associated Flex recipe, registered via a PR to https://github.com/symfony/recipes-contrib

**Comment by theofidry** [comment]
Thanks for checking this out @FGM.

I would love Flex to be a bit more flexible and allow a simple config entry in the `composer.json` like they do with [service providers in Laravel](https://medium.com/@taylorotwell/package-auto-discovery-in-laravel-5-5-ea9e3ab20518), but meanwhile I guess a recipe will be required.

Regarding the second issue that sounds much weirder...

**Comment by FGM** [comment]
Yes, this seems to be heavily requested, judging from issues on the Flex repo, but fabpot is firm on this for now. That's one good thing with Laravel 5 service providers (or Drupal modules, BTW) indeed.

**Comment by theofidry** [comment]
To be honest I would like the `psysh` alias so let's make a recipe for it
