### ISSUE TITLE
psysh is not properly formatting tags (4.3.0)

### ISSUE THREAD

**Issue by jaumebecks** [theofidry/PsyshBundle#57]
Hi! I've been struggling with the latest version of this bundle because is not properly formatting the tags, as shown here:

![Screenshot from 2020-11-11 16-27-15](https://user-images.githubusercontent.com/22539671/98831877-6bca7480-243c-11eb-880f-e5560ae64ab2.png)

As you can see, html tags are not formatted properly, and it also applies when I run `ls` command and other functionalities.

I'm running it in a php7.3 container. 
It could be a psysh problem rather than an issue of this project, so to verify it I made a custom command 
that used Psy directly rather than using the command that provides this bundle:
```php
<?php
namespace App\Common\Command;

use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use function Psy\debug;

class PsyCommand extends Command
{
    protected function configure()
    {
        $this->setName('hat:psysh');
        $this->setDescription('Launch an interactive php shell with Symfony loaded');
        $this->setHelp('Syntax: php bin/console hat:psysh');
    }

    protected function execute(InputInterface $input, OutputInterface $output)
    {
        $application = $this->getApplication();
        $container = $application->getKernel()->getContainer();
        $kernel = $application->getKernel();
        $parameters = $container->getParameterBag()->all();
        $application->setCatchExceptions(false);
        $application->setAutoExit(false);

        // Seems like less has a problem in the docker image
        debug(get_defined_vars(), get_called_class());
        // Type `help` or `?` in the console to see the available commands
    }
}

```

So when I run `bin/console hat:psysh` I get this result:
![Screenshot from 2020-11-11 16-44-49](https://user-images.githubusercontent.com/22539671/98832562-425e1880-243d-11eb-88d8-3ff0fe7bac4d.png)

Which seems that is working properly.

Could you bring some light here @theofidry? 
Let me know if there's any extra information you need, thanks in advance!

**Comment by theofidry** [comment]
That is very curious... Could you check if the same happens when you call `Fidry\PsyshBundle\psysh()` instead of `Psy\debug\debug`?

**Comment by jaumebecks** [comment]
```php

        PsyshFacade::debug(get_defined_vars(), get_called_class());
```

**Comment by jaumebecks** [comment]
I tried it with 
- `\PsyshBundle\psysh(get_defined_vars(), get_called_class());` 
and
- `Fidry\PsyshBundle\PsyshFacade::debug(get_defined_vars(), get_called_class())`

![image](https://user-images.githubusercontent.com/22539671/99048362-bf9ca100-2595-11eb-908f-8af2bb679c75.png)

but it seems still to be working fine

**Comment by theofidry** [comment]
So somehow this has to do with the command not how Psysh is configured...

**Comment by jaumebecks** [comment]
Correct! Do you have any idea why this could happen?

**Comment by theofidry** [comment]
Nope. But at least we confirmed that:

- you have a command where it works
- Psysh is not too blame

I'm not sure why the current command gives this word behaviour but maybe it's not going to be too hard to fix?

**Comment by jaumebecks** [comment]
Just to give more info about it, I did a test directly changing the vendor command `vendor/theofidry/psysh-bundle/src/Command/PsyshCommand.php`, adding the Psy call as follows
![Screenshot from 2020-11-18 10-27-33](https://user-images.githubusercontent.com/22539671/99512540-dffb9f80-2989-11eb-960e-1244e90087af.png)

and this is the result when I run `bin/console psysh`:

![Screenshot from 2020-11-18 10-25-09](https://user-images.githubusercontent.com/22539671/99512620-f99ce700-2989-11eb-997e-d03af7ac77e3.png)

the first call works (\Psy\debug), not the next one (\Symfony\Component\Console\Application::run). I'm still figuring out why...

**Comment by allan-simon** [comment]
I can confirm I got the same issue , with a brand new install of psyshbundle , I also got the html directly outputed

**Comment by dvthjkr** [comment]
Hint : it seems that for many commands, the required OutPutInterface ($output) is charged with a "basic" instance from Symfony, instead of a proper Psy\Output\ShellOutput instance. 

I managed to "solve" the issue by commenting lines 309 and 311 in psy/psysh/src/Shell.php 
        //if ($output === null) {
            $output = $this->config->getOutput();
        //}
=> this reloads the OutputInterface expected by the config each time. Of course, performance-wise, this is not an appropriate solution. But I hope this helps you find the appropriate solution. 
NB : i had a problem by running "help ls", while the "page" method is available only with a ShellOuput and not with OutputInterface

**Comment by theofidry** [comment]
Closed by #72

**Comment by mutedMike** [comment]
Would it be possible to merge that to 4.4.0 and make a bugfix release out of it? Or php7 is not supported anymore and I should fork it?

**Comment by mutedMike** [comment]
@theofidry Would it be possible to merge https://github.com/theofidry/PsyshBundle/pull/72 into 4.4.0 and make a bugfix release out of it? (I'm still running php7.4 in some projects)
