### ISSUE TITLE
Executing bootstrap process after variable initialization

### ISSUE THREAD

**Issue by Charl13** [theofidry/PsyshBundle#66]
Hi,

Is there a way to execute code using pre-configured variables like `$container` each time the shell starts?

One of the scenario's I'd like to achieve on entering the shell is:

```php
$entityManager = $container->get(\Doctrine\ORM\EntityManagerInterface::class);
$user = $entityManager->find(\App\Entity\User::class, 1);
$storage = $container->get('security.token_storage');

$token = new \Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken(
    $user,
    $user->getPassword(),
    'main',
    $user->getRoles()
);
$storage->setToken($token);
```

**Comment by theofidry** [comment]
>Is there a way to execute code using pre-configured variables like $container each time the shell starts?

Yes like so:

https://github.com/theofidry/PsyshBundle#adding-custom-variables

Feel free to re-open an issue if there is a problem there
