### ISSUE TITLE
Is the high Symfony version requirement necessary? 

### ISSUE THREAD

**Issue by dlancea** [theofidry/PsyshBundle#7]
Is this project using something unique to Symfony 2.7? I'm locked out from using it because I'm still using the previous LTS release, 2.3.

**Comment by theofidry** [comment]
I tested it a little and seems to work. You can try it using the `dev-symfony-2.3` branch and tell me if it's good for you too (I didn't test much so I prefer to wait for your confirmation).

If it's good I'll merge the PR #8.

**Comment by dlancea** [comment]
I've tested for the last few hours and ran through the examples listed in the docs (https://github.com/theofidry/PsyshBundle/tree/master/Resources/doc) and haven't run into any problems.

**Comment by theofidry** [comment]
Perfect :)

**Comment by theofidry** [comment]
It's safe to use the branch `dev-master` if you wish to get the last commit for that. There is not BC break in sight for now.

**Comment by theofidry** [comment]
Edit: I updated the release.

**Comment by dlancea** [comment]
:+1:
